-- 코드를 입력하세요
SELECT
    BOARD.TITLE,
    REPLY.BOARD_ID,
    REPLY.REPLY_ID,
    REPLY.WRITER_ID,
    REPLY.CONTENTS,
    DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_REPLY REPLY
INNER JOIN
    USED_GOODS_BOARD BOARD
ON
    BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE
    BOARD.CREATED_DATE LIKE '2022-10%'
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC;